version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      retries: 5
      timeout: 3s
          
  web:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    container_name: django
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_data:/app/staticfiles
volumes:
  postgres_data:
  static_data:

#  system:  
#    build:
#      context: .
#      dockerfile: Dockerfile.system  
#    image: system 
#    restart: "no" 